export const TOASTIE_FACTS = {
  en: [
    "Grated cheese melts more evenly because the smaller pieces have more surface area.",
    "That golden-brown crunch comes from the Maillard reaction between heat, sugars and proteins.",
    "Letting a toastie rest for one minute helps the cheese settle before the first bite.",
    "A preheated iron crisps the bread quickly, before the middle has time to dry out.",
    "Steam softens toast, so leave a finished toastie uncovered if you want it to stay crisp.",
    "A thin, even layer of butter helps the whole surface brown instead of only a few patches.",
    "Cheese melts from the outside in, which is why thin slices beat one big chunk.",
    "Pickles taste great in a toastie because their acidity balances the richness of melted cheese.",
    "Cutting a toastie diagonally exposes more of its glorious melted-cheese cross-section.",
    "Mixing a bold cheese with a mild melty one gives you both flavour and a better cheese pull.",
    "Bread stays crispest when the filling is not too wet and reaches right to the edges.",
    "The smell of a hot toastie travels easily because warmth releases more aroma molecules.",
    "Gentle heat gives the cheese time to melt before the bread gets too dark.",
    "Too much heat can burn the outside while the centre is still stubbornly cold.",
    "Cheese that is not fridge-cold reaches its melting point sooner.",
    "Mozzarella stretches well because heating loosens its elastic protein network.",
    "Aged cheddar brings stronger flavour, but it usually stretches less than young cheese.",
    "Sourdough's tangy flavour is especially good at balancing rich melted cheese.",
    "Mustard adds acidity and sharpness without adding much moisture.",
    "Mayonnaise browns bread well because it is mostly an emulsion of oil and egg.",
    "Butter contains milk solids that add a nutty flavour as the bread browns.",
    "Even contact with the hot plate produces more even browning and clearer grill marks.",
    "Rotating a toastie halfway through can compensate for an iron with uneven hot spots.",
    "Pressing too hard can squeeze the best part of the filling straight out of the bread.",
    "An overfilled toastie heats less evenly and has a much greater chance of cheese escape.",
    "Leaving a narrow empty border around the filling helps keep molten cheese inside.",
    "Escaped cheese is not always a tragedy: it can fry into a crispy frico-like edge.",
    "Blotting tomato slices removes surface water that would otherwise soften the toast.",
    "Cooking mushrooms first removes water and concentrates their savoury flavour.",
    "Wilted, well-drained spinach makes a crisper filling than raw wet leaves.",
    "Caramelised onions contain less water than raw onions, so they are kinder to crunchy bread.",
    "Meat fillings should already be fully cooked; a toastie iron is best used for reheating them.",
    "A toastie keeps cooking briefly after leaving the iron because of residual heat.",
    "Cooling a toastie on a wire rack keeps steam from softening its underside.",
    "A flat plate traps a little steam beneath hot toast, which slowly softens the bottom crust.",
    "A serrated knife cuts crisp bread with less crushing than a blunt straight-edged knife.",
    "On square bread, a diagonal cut creates a longer exposed filling edge than a straight cut.",
    "Small, evenly distributed cheese pieces melt without leaving cold lumps in the middle.",
    "Softened butter spreads thinly without tearing holes in delicate bread.",
    "More fat is not always crisper; thick pools can leave the bread heavy and greasy.",
    "Cheese is already salty, so taste the filling before adding another pinch.",
    "Dried herbs release lots of aroma into warm fat, while fresh herbs bring a brighter taste.",
    "Fat carries many flavour compounds, which is one reason melted cheese smells so powerful.",
    "Mozzarella plus cheddar is a classic partnership: one stretches and the other brings punch.",
    "Gouda melts smoothly because its balance of moisture and fat is particularly toastie-friendly.",
    "Low-moisture mozzarella gives a strong cheese pull without making the bread as wet.",
    "Fresh mozzarella benefits from a quick blot before it goes anywhere near the bread.",
    "Parmesan boosts savoury flavour, but melts best when paired with a softer cheese.",
    "Thicker bread supports heavier fillings, but the heat takes longer to reach the centre.",
    "Soft bread compresses against the iron, increasing contact and creating an even crust.",
    "Dense bread warms more slowly than airy bread, so its filling may need extra grill time.",
    "Dark bread makes browning harder to judge by colour, so aroma and timing become more useful.",
    "Grill ridges appear most clearly where the bread makes firm, direct contact with the plate.",
    "Spreading filling evenly prevents one cold corner and one volcanic cheese pocket.",
    "Small pieces of filling heat faster and more evenly than large chunks.",
    "Warm fillings shorten grill time because the iron does not need to heat them from fridge temperature.",
    "Fridge-cold fillings need more time, even when the bread already looks perfectly toasted.",
    "Acidic condiments such as chutney, mustard and pickles cut through rich cheese.",
    "The Maillard reaction is named after French chemist Louis-Camille Maillard.",
    "Much of flavour is actually aroma travelling from your mouth to your nose while you chew.",
    "Slightly stale bread can be useful: its firmer structure absorbs filling without collapsing as quickly.",
    "Toasting drives moisture from the bread's surface, helping it become firm and crisp.",
    "The sound of a crunch can influence how fresh and crispy food seems to us.",
    "The names vary by place: 'toastie' is common in Britain, while the Dutch usually say 'tosti'.",
  ],
  nl: [
    "Geraspte kaas smelt gelijkmatiger doordat de kleine stukjes samen meer oppervlak hebben.",
    "Dat goudbruine korstje ontstaat door de Maillardreactie tussen hitte, suikers en eiwitten.",
    "Laat een tosti een minuut rusten, dan kan de kaas even tot bedaren komen voor de eerste hap.",
    "Een voorverwarmd ijzer maakt het brood snel krokant voordat de binnenkant uitdroogt.",
    "Stoom maakt toast zacht, dus laat een verse tosti onbedekt als hij krokant moet blijven.",
    "Een dun, gelijkmatig laagje boter laat de hele buitenkant bruinen in plaats van losse plekjes.",
    "Kaas smelt van buiten naar binnen; dunne plakjes werken daarom beter dan een groot blok.",
    "Augurk past goed in een tosti omdat het zuur de volle smaak van gesmolten kaas in balans brengt.",
    "Een diagonale snede laat extra veel van die glorieuze gesmolten-kaasdoorsnede zien.",
    "Combineer een pittige kaas met een milde smeltkaas voor veel smaak en een betere cheese pull.",
    "Brood blijft het krokantst als de vulling niet te nat is en netjes tot aan de randen komt.",
    "De geur van een hete tosti verspreidt zich snel doordat warmte meer aromamoleculen vrijlaat.",
    "Rustige hitte geeft de kaas tijd om te smelten voordat het brood te donker wordt.",
    "Te veel hitte kan de buitenkant verbranden terwijl het midden nog koppig koud is.",
    "Kaas die niet koelkastkoud is, bereikt eerder zijn smeltpunt.",
    "Mozzarella trekt goede draden doordat verhitting het elastische eiwitnetwerk losser maakt.",
    "Gerijpte cheddar smaakt sterker, maar trekt meestal minder draden dan jonge kaas.",
    "De frisse smaak van zuurdesem brengt volle gesmolten kaas mooi in balans.",
    "Mosterd voegt zuur en pit toe zonder de vulling veel natter te maken.",
    "Mayonaise laat brood goed bruinen doordat het vooral een emulsie van olie en ei is.",
    "Boter bevat melkbestanddelen die tijdens het bruinen een nootachtige smaak geven.",
    "Gelijkmatig contact met de hete plaat geeft een egaler korstje en duidelijkere grillstrepen.",
    "Een tosti halverwege draaien helpt als het ijzer niet overal even heet wordt.",
    "Te hard drukken kan het beste deel van de vulling zo uit het brood persen.",
    "Een overvolle tosti warmt minder gelijkmatig op en heeft veel meer kans op ontsnappende kaas.",
    "Een smal leeg randje rond de vulling helpt om gesmolten kaas binnen te houden.",
    "Ontsnapte kaas is niet altijd tragisch: hij kan bakken tot een krokant frico-achtig randje.",
    "Dep plakjes tomaat droog, anders maakt het oppervlaktewater de toast zachter.",
    "Bak champignons eerst om water te verwijderen en hun hartige smaak te concentreren.",
    "Geslonken, goed uitgelekte spinazie geeft een krokantere vulling dan natte rauwe blaadjes.",
    "Gekaramelliseerde ui bevat minder water dan rauwe ui en is dus vriendelijker voor krokant brood.",
    "Vleesvulling moet al gaar zijn; een tosti-ijzer is vooral geschikt om die opnieuw op te warmen.",
    "Een tosti gaart na het ijzer nog heel even door dankzij de overgebleven warmte.",
    "Laat een tosti afkoelen op een rooster, dan maakt stoom de onderkant minder snel zacht.",
    "Op een plat bord blijft wat stoom onder hete toast hangen, waardoor de bodem langzaam zachter wordt.",
    "Een kartelmes snijdt krokant brood met minder pletten dan een bot glad mes.",
    "Bij vierkant brood geeft een diagonale snede een langere zichtbare vullingsrand dan een rechte snede.",
    "Kleine, gelijkmatig verdeelde stukjes kaas smelten zonder koude klonten in het midden.",
    "Zachte boter smeert dun uit zonder gaten in kwetsbaar brood te trekken.",
    "Meer vet is niet altijd krokanter; dikke plassen kunnen brood zwaar en vettig maken.",
    "Kaas is van zichzelf al zout, dus proef de vulling voordat er nog een snuf bij gaat.",
    "Gedroogde kruiden geven veel aroma af aan warm vet, terwijl verse kruiden frisser smaken.",
    "Vet draagt veel smaakstoffen, en daarom kan gesmolten kaas zo krachtig ruiken.",
    "Mozzarella en cheddar zijn een klassiek duo: de ene trekt draden en de andere geeft pit.",
    "Gouda smelt soepel doordat de verhouding tussen vocht en vet erg tosti-vriendelijk is.",
    "Mozzarella met weinig vocht geeft een sterke cheese pull zonder het brood zo nat te maken.",
    "Verse mozzarella wordt beter van een korte depbeurt voordat hij bij het brood komt.",
    "Parmezaan geeft extra hartige smaak, maar smelt het best samen met een zachtere kaas.",
    "Dikker brood ondersteunt zwaardere vullingen, maar de warmte bereikt het midden langzamer.",
    "Zacht brood wordt tegen het ijzer gedrukt, maakt meer contact en krijgt zo een gelijkmatig korstje.",
    "Dicht brood warmt langzamer op dan luchtig brood, dus de vulling heeft soms extra tijd nodig.",
    "Bij donker brood is bruining lastiger aan de kleur te zien; geur en timing worden dan belangrijker.",
    "Grillstrepen zijn het duidelijkst waar het brood stevig en direct contact maakt met de plaat.",
    "Een gelijkmatig verdeelde vulling voorkomt één koude hoek en één vulkanische kaaszak.",
    "Kleine stukjes vulling worden sneller en gelijkmatiger warm dan grote brokken.",
    "Warme vulling verkort de baktijd omdat het ijzer niet vanaf koelkasttemperatuur hoeft te beginnen.",
    "Koelkastkoude vulling heeft meer tijd nodig, ook als het brood er al perfect geroosterd uitziet.",
    "Zure smaakmakers zoals chutney, mosterd en augurk snijden mooi door volle kaas heen.",
    "De Maillardreactie is vernoemd naar de Franse scheikundige Louis-Camille Maillard.",
    "Een groot deel van smaak is eigenlijk aroma dat tijdens het kauwen van je mond naar je neus reist.",
    "Iets ouder brood kan handig zijn: de stevigere structuur neemt vulling op zonder snel in te zakken.",
    "Roosteren verdrijft vocht uit het broodoppervlak, waardoor het stevig en krokant wordt.",
    "Het geluid van een krakende korst kan beïnvloeden hoe vers en krokant eten voor ons voelt.",
    "De naam verschilt per plek: in Groot-Brittannië zegt men vaak 'toastie', in Nederland meestal 'tosti'.",
  ],
} as const;
